apiVersion: apps/v1
kind: Deployment
metadata:
      name: login-app-deployment
spec:
    replicas: 1
    selector:
      matchLabels:
        app: login-app
    template:
      metadata:
        labels:
          app: login-app
      spec:
        containers:
          - name: login-app
            image: 557523153113.dkr.ecr.ap-south-1.amazonaws.com/login-app-backend:latest
            ports:
            - containerPort: 8085
        imagePullSecrets:
        - name: ecr-secret
---
apiVersion: v1
kind: Service
metadata:
      name: login-app
spec:
    ports:
      - port: 8085
        targetPort: 8085
    selector:
        name: login-app