apiVersion: v1
kind: ReplicationController
metadata:
    lables:
      name: login-app-backend-controller
    name: login-app
spec:
    replicas: 1
    template:
     metadata:
        labels:
        name: login-app
    spec:
        containers:
        - image: 557523153113.dkr.ecr.ap-south-1.amazonaws.com/login-app-backend
          name: login-app
          ports:
          - name: login-app
            containerPort: 8085
---
#service to expose outside
apiVersion: v1
kind: Service
metadata:
    lables:
      name: login-app
    name: login-app
spec:
    type: NodePort
    ports:
      - port: 8085
        targetPort: 8085
    selector:
        name: login-app

